# Clippy configuration for rust2mojo

# Avoid false positives
too-many-arguments-threshold = 8
type-complexity-threshold = 500

# Performance tuning
avoid-breaking-exported-api = false
msrv = "1.87.0"

# Documentation settings
missing-docs-in-crate-items = true