# rustfmt configuration for rust2mojo

# Basic formatting options
edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4

# Import formatting
reorder_imports = true

# Code style
newline_style = "Unix"

# Function formatting
fn_params_layout = "Tall"

# Misc
remove_nested_parens = true
use_field_init_shorthand = true
force_explicit_abi = true