# rustfmt configuration for rust2mojo

# Basic formatting options
edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4

# Import formatting
imports_granularity = "Crate"
reorder_imports = true
group_imports = "StdExternalCrate"

# Code style
newline_style = "Unix"
format_code_in_doc_comments = true
format_strings = true

# Function formatting
fn_args_layout = "Tall"
brace_style = "SameLineWhere"

# Control flow
control_brace_style = "AlwaysSameLine"

# Comments and documentation
normalize_comments = true
normalize_doc_attributes = true
wrap_comments = true
comment_width = 100

# Misc
remove_nested_parens = true
use_field_init_shorthand = true
force_explicit_abi = true